### Show number of registrations and registration form <1>
GET {{baseurl}}/registration?eventId={{eventId}}

### Register new participant <2>
POST {{baseurl}}/registration
Content-Type: application/x-www-form-urlencoded

eventId={{eventId}}&name=Gerd&email=gerd@aschemann.net

### Upload additional webinar data to event <3>
PUT {{baseurl}}/admin/events/{{eventId}}/data
Content-Type: application/json

{"webinarLink" : "https://example.com/webinar"}

### Send e-mail message to participants <4>
PUT {{baseurl}}/admin/events/{{eventId}}/message
Content-Type: application/json

{"subject" : "Event XXX", "summary" : "Herzlich willkommen", "registrationIds" : []}

### Show overview of events <5>
GET {{baseurl}}/admin/events

### Show registrations of one event <6>
GET {{baseurl}}/admin/events/{{eventId}}

### Show Webinar data <7>
GET {{baseurl}}/webinar/{{eventId}}

### Delete my registration - You need to append the registration UUID received in #<2> <8>
DELETE {{baseurl}}/delete?id=3053214b-39fb-448a-8dbb-eb148c984a99

### Delete my registration by date and mail address <9>
POST {{baseurl}}/delete
Content-Type: application/x-www-form-urlencoded

eventId={{eventId}}&email=gerd@aschemann.net

### Delete my registration - You need to append the event id and the registration UUID received in #<2> <10>
GET {{baseurl}}/delete?eventId={{eventId}}&id=e6c05d25-0c3e-4974-810c-62c408d88d09
