package de.jugda.registration.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.Date;
import java.util.Map;

/**
 * @author Niko Köbler, http://www.n-k.de, @dasniko
 */
@Data
@DynamoDBTable(tableName = "jugda-registration")
public class Registration {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute
    private String id;
    @DynamoDBAttribute
    private String eventId;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private String twitter;
    @DynamoDBAttribute
    private boolean pub;
    @DynamoDBAttribute
    private boolean privacy;
    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp
    private Date created;
    @DynamoDBAttribute
    private Long ttl;

    public static Registration of(Map<String, Object> model) {
        String eventId = model.get(RequestParam.EVENT_ID).toString();
        Registration registration = new Registration();
        registration.setEventId(eventId);
        registration.setName(model.get(RequestParam.NAME).toString().trim());
        registration.setEmail(model.get(RequestParam.EMAIL).toString().trim().toLowerCase());
        registration.setTwitter(model.getOrDefault(RequestParam.TWITTER, "").toString().trim().toLowerCase());
        registration.setPub(model.getOrDefault(RequestParam.PUB, "off").toString().equalsIgnoreCase("on"));
        registration.setPrivacy(model.getOrDefault(RequestParam.PRIVACY, "off").toString().equalsIgnoreCase("on"));
        registration.setTtl(LocalDate.parse(eventId).plusDays(14).atStartOfDay().toEpochSecond(ZoneOffset.UTC));
        return registration;
    }
}
